### ISSUE TITLE
No se puede realizar una votación

### ISSUE THREAD

**Issue by javierbonillad** [EGC1617Grupo/agora-gui-elections#1]
Cuando se crea una elección, ya sea pública o privada, en el paso correspondiente a la votación no se puede avanzar ya que no se recibe el código necesario para realizar el voto.

**Comment by alvarovp27** [comment]
Como no tenemos ni un servidor de correo ni un servidor de SMS, tenemos que comprobar los códigos generados a través de los logs en la consola. Para ello, dentro de la máquina de agora voting, mediante SSH, ejecutaremos este comando para supervisar los logs:
```
sudo supervisorctl tail -f authapi_celery
```
