### ISSUE TITLE
El código localizador de papeleta se sale de la pantalla

### ISSUE THREAD

**Issue by javierbonillad** [EGC1617Grupo/agora-gui-elections#14]
En la vista correspondiente al Ballot-Tracker, la cual tiene una URL como la que sigue:
[https://agora/election/{id-eleccion}/public/ballot-locator](url)

- Cuando se hace más pequeño el ancho de pantalla, en lo que podría corresponder a un iPhone 4, el código se sale de la pantalla, no permitiendo visualizarlo por completo.

- Se está trabajando sobre la rama feature/responsive.

- Se adjunta imagen con el problema
![image](https://cloud.githubusercontent.com/assets/22940221/20626636/54908a84-b31b-11e6-8e8c-276d80bf5cfb.png)

**Comment by danimm08** [comment]
La incidencia se ha solucionado en el siguiente commit 630d41a8022093af4e916f7636847028c908f9e5

Adjunto una imagen con la solución del problema:
![image](https://cloud.githubusercontent.com/assets/22836426/20866298/9b8cc16c-ba2a-11e6-88fb-254628140f1a.png)
