### ISSUE TITLE
Mostrar únicamente preguntas que tengas votos

### ISSUE THREAD

**Issue by alvarovp27** [EGC1617Grupo/agora-gui-elections#25]
Se sugiere la siguiente mejora:
- En la vista de resultados de la elección, mostrar en las tablas únicamente aquellos candidatos que hayan obtenido al menos un voto válido.
- La URI de la vista es la siguiente: https://agora/election/{id}/public/home
- Se adjunta una captura de pantalla indicando la zona de la mejora:

**Comment by juandjara** [comment]
Voy a implementar esto

**Comment by juandjara** [comment]
Esto se ha implementado en el commit https://github.com/EGC1617Grupo/agora-gui-elections/commit/0189ce7ba3db0b934869c64d4aece39eaa4406ab

**Comment by juandjara** [comment]
Volvemos a abrir la issue porque el cambio no se arreglo correctamente

**Comment by juandjara** [comment]
Esta issue se ha comprobado que esta arreglada en el commit https://github.com/EGC1617Grupo/agora-gui-elections/commit/1608ab20eb3161cf3ea85f0fcc717577edb5af0a
