### ISSUE TITLE
Vagrant provision falla en la máquina agora

### ISSUE THREAD

**Issue by migrodcab** [EGC1617Grupo/agora-gui-elections#4]
Al realizar el Vagrant Provision en la máquina agora da un fallo en el archivo cMake de la carpeta Sentry.

**Comment by alvarovp27** [comment]
Esta incidencia fue solucionada, tomando la rama master del repositorio agora-dev-box, y cambiando el fichero sentry/package.yml de la rama master por el de la rama next.
